---
title: "Spatial Grouping Discrepancy (SGD)"
output: html_document
---


# Installation

To install the package from GitHub, use the following command:

```r
# Install the package from GitHub
if (!requireNamespace("devtools", quietly = TRUE)) {
  install.packages("devtools")
}
devtools::install_github("YihDu/SGD")
```

# Spatial Grouping Discrepancy (SGD)

SGD provides a unbiased clustering evaluation metric for spatial transcriptomics data. 
It accounts for the label agreement between the clustering results and the ground truth, spatial label distribution, and the mislabel severity simultaneously.

```r
library(SGD)
SGD(true_labels, cluster_labels, spatial_coordinates)
```

## Parameters
- **true_labels** : numeric or factor
Ground truth labels of the dataset. These represent the actual class labels that we wish to compare with the predicted clusters.

- **cluster_labels** : numeric or factor
The predicted labels or clusters generated by the clustering algorithm. These are the labels that the model outputs and will be compared with the true labels.

- **spatial_coordinates** : matrix or data.frame
A matrix or data frame that contains the spatial or positional coordinates of the data points. These coordinates are used to account for the spatial relationships in the analysis.

- **params** : list (optional)
A list of additional parameters that control the behavior of the function. 

# Example Usage

```r
# Example code here
```








